### PR TITLE
SUS-1128 - JSON Serialization Performance Enhancement

### PR DESCRIPTION
**Pull request by jogura**
Profiling revealed that JSON serialization was a hotspot taking a considerable amount of time. I tried two different 3rd party JSON libraries GSON and play-json. Both were better than the built-in scala.json library in terms of performance and play-json was considerably faster than GSON.
- Switch built-in JSON serializer to play-json
- Store hostname once and use multiple times (another hotspot)
- Add unittest for methods that serialization changes

Anyone with Scala expertise is welcome to comment since I am not familiar with the "scala way" 😄

### CODE REVIEW

**Comment by TK-999** [comment]
Looks good! @macbre what do you think?

**Comment by macbre** [comment]
Quoting @jogura - I know almost nothing about _The Scala Way_ :)

**Comment by TK-999** [comment]
@macbre @jogura one thing we might want to consider is stopping `/match` method on first match and returning JSON object of first matched block instead of an array. Looking at the extension code, we use the first match in all cases when we're matching input against the service, except for Phalanx filter test mode - so it might make sense to use a separate endpoint for test mode.

**Comment by macbre** [comment]
@TK-999, are we sure that no other clients (like Helios) rely on the `/match` response format?

**Comment by TK-999** [comment]
according to Confluence Helios uses `/check` method - we should definitely verify though

**Pull request merged**
